import { r } from '@rebuilder/system';

export const metadata = {
  title: 'Init',
  path: '/init',
  requireAuth: false,
  layout: 'default',
};

export default function InitPage() {
  return r.div(
    r.h1('Init'),
    r.p('This page was generated by Rebuilder'),
    
    // Example: Button with click handler
    r.button(
      { onClick: () => console.log('Init clicked!') },
      'Click Me',
    ),
    
    // Example: State management
    // const count = useState(0);
    // r.span(count.value),
    
    // Example: Navigation
    // router.navigate('/dashboard');
  );
}
