import type { RouteContext } from '@rebuilder/config/config';
import { r } from '@rebuilder/system';

export const metadata = {
  title: 'Help',
  path: '/--help',
  requireAuth: false,
  layout: 'default',
};

export default function HelpPage(
  context?: RouteContext
) {
  return r.div(
    { className: 'p-6 max-w-4xl mx-auto space-y-4' },

    r.h1(
      { className: 'text-2xl font-bold text-gray-900' },
      'Help'
    ),

    r.p(
      { className: 'text-gray-600' },
      'This page was generated by Rebuilder'
    ),

    // Example: Query & dynamic parameter display
    context?.params &&
    Object.keys(context.params).length > 0
      ? r.p(
          {
            className:
              'text-sm text-blue-600 font-mono'
          },
          'Params: ' +
            JSON.stringify(context.params)
        )
      : null,

    // Example: Button with click handler
    r.button(
      {
        className:
          'px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition cursor-pointer',

        onClick: () =>
          console.log('Help clicked!')
      },
      'Click Me'
    )
  );
}
