import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
export async function createRouter(name) {
    // ----------------------------------------
    // 1. Folder name
    // ----------------------------------------
    // Example:
    // sign-in -> sign-in
    // homeMain -> home_main
    const folderName = name
        .replace(/([A-Z])/g, '_$1')
        .toLowerCase()
        .replace(/^_/, '');
    // ----------------------------------------
    // 2. Component name
    // ----------------------------------------
    // Convert:
    // sign-in -> SignIn
    // sign_in -> SignIn
    // home-main -> HomeMain
    // homeMain -> HomeMain
    const componentName = name
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');
    // ----------------------------------------
    // 3. Route path
    // ----------------------------------------
    // Example:
    // sign-in -> /sign-in
    // homeMain -> /home-main
    const routePath = '/' + name.replace(/([A-Z])/g, '-$1').toLowerCase();
    // ----------------------------------------
    // 4. Create router folder
    // ----------------------------------------
    const folderPath = path.join(process.cwd(), 'src', 'routing', folderName);
    await fs.ensureDir(folderPath);
    // ----------------------------------------
    // 5. Generate page
    // ----------------------------------------
    const pageContent = generatePage(componentName, routePath);
    await fs.writeFile(path.join(folderPath, 'index.ts'), pageContent);
    // ----------------------------------------
    // 6. Generate configuration
    // ----------------------------------------
    const configContent = generateConfig(componentName, routePath);
    await fs.writeFile(path.join(folderPath, 'system_configuration.ts'), configContent);
    // ----------------------------------------
    // 7. Success message
    // ----------------------------------------
    console.log(chalk.green(`✅ Created router: ${folderName}`));
    console.log(chalk.gray(`   📄 src/routing/${folderName}/index.ts`));
    console.log(chalk.gray(`   ⚙️  src/routing/${folderName}/system_configuration.ts`));
}
// ==================================================
// PAGE GENERATOR
// ==================================================
function generatePage(componentName, routePath) {
    return `import type { RouteContext } from '../../config/config';

export const metadata = {
  title: '${componentName}',
  path: '${routePath}',
  requireAuth: false,
  layout: 'default',
};

export default function ${componentName}Page(
  context?: RouteContext
) {
  return r.div(
    { className: 'p-6 max-w-4xl mx-auto space-y-4' },

    r.h1(
      { className: 'text-2xl font-bold text-gray-900' },
      '${componentName}'
    ),

    r.p(
      { className: 'text-gray-600' },
      'This page was generated by Rebuilder'
    ),

    // Example: Query & dynamic parameter display
    context?.params &&
    Object.keys(context.params).length > 0
      ? r.p(
          {
            className:
              'text-sm text-blue-600 font-mono'
          },
          'Params: ' +
            JSON.stringify(context.params)
        )
      : null,

    // Example: Button with click handler
    r.button(
      {
        className:
          'px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition cursor-pointer',

        onClick: () =>
          console.log('${componentName} clicked!')
      },
      'Click Me'
    )
  );
}
`;
}
// ==================================================
// SYSTEM CONFIGURATION GENERATOR
// ==================================================
function generateConfig(componentName, routePath) {
    return `export default {
  path: '${routePath}',
  title: '${componentName}',

  window: {
    width: 1200,
    height: 800,
    minWidth: 600,
    minHeight: 400,
    resizable: true,
    fullscreenable: true,
    title: '${componentName}',
  },

  layout: 'default',
  requireAuth: false,
  transition: 'fade',
  duration: 300,
};
`;
}
